name = "wavelite-signaling"
main = "signaling.js"
compatibility_date = "2024-01-01"

# Optional: Add KV namespace for persistent storage
# [[kv_namespaces]]
# binding = "SIGNALING_STORE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Optional: Add environment variables
# [vars]
# ENVIRONMENT = "production"

# Optional: Add routes for custom domain
# routes = [
#   { pattern = "signaling.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
